---
- name: Playbook to send data, accepts parameters
  hosts: dev
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/../group_vars/common.yml"
    - "{{playbook_dir}}/../group_vars/df.yml"
  roles:
    - "{{playbook_dir}}/../roles/common"
    - "{{playbook_dir}}/../roles/build_framework/clone_core"
    - "{{playbook_dir}}/../roles/build_framework/build_logs"

